In [3]:
import pandas as pd
# Existing DataFrame
df = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "First Name": ["Rohan", "Priya", "Ankit"],
    "Department": ["HR", "IT", "Sales"],
    "Monthly Salary": [45000, 55000, 50000],
    "Experience": [2, 5, 3]
})

# New employees
new_employee = pd.DataFrame([
    {
        "Emp_ID": 108,
        "Name": "Kiran",
        "Department": "IT",
        "Monthly Salary": 0.0,
        "Experience": 3
    },
    {
        "Emp_ID": 109,
        "Name": "Amitav",
        "Department": "Accounts",
        "Salary": 0.0,
        "Experience": 0
    }
])

# Append new employees
df = pd.concat([df, new_employee], ignore_index=True)

print(df)

   Emp_ID First Name Department  Monthly Salary  Experience    Name  Salary
0     101      Rohan         HR         45000.0           2     NaN     NaN
1     102      Priya         IT         55000.0           5     NaN     NaN
2     103      Ankit      Sales         50000.0           3     NaN     NaN
3     108        NaN         IT             0.0           3   Kiran     NaN
4     109        NaN   Accounts             NaN           0  Amitav     0.0

In [4]:
print(df.isnull().sum())

Emp_ID            0
First Name        2
Department        0
Monthly Salary    1
Experience        0
Name              3
Salary            4
dtype: int64

In [21]:
df.fillna(4, inplace=True)

KeyError: "None of ['Name'] are in the columns"

In [9]:
df

   Emp_ID First Name Department  Monthly Salary  Experience    Name  Salary
0     101      Rohan         HR         45000.0           2     NaN     NaN
1     102      Priya         IT         55000.0           5     NaN     NaN
2     103      Ankit      Sales         50000.0           3     NaN     NaN
3     108        NaN         IT             0.0           3   Kiran     NaN
4     109        NaN   Accounts             NaN           0  Amitav     0.0

In [18]:
import pandas as pd
import numpy as np

# Sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [2, np.nan, np.nan, 3]
})
# print(df)

# Fill NaN with column mean
df = df.fillna(df.mean())

print(df)

          A    B
0  1.000000  2.0
1  2.000000  2.5
2  2.333333  2.5
3  4.000000  3.0

In [20]:
df.set_index('A', inplace=True)
df

            B
A
1.000000  2.0
2.000000  2.5
2.333333  2.5
4.000000  3.0

In [27]:
group=df.groupby("A")["B"].count()
print(group)

A
1.000000    1
2.000000    1
2.333333    1
4.000000    1
Name: B, dtype: int64

In [28]:
group=df.groupby("A")["B"].mean()
print(group)

A
1.000000    2.0
2.000000    2.5
2.333333    2.5
4.000000    3.0
Name: B, dtype: float64

In [32]:
print(df["B"].mean())

2.5

In [33]:
print(df["B"].median())

2.5

In [34]:
print(df["B"].mode())

0    2.5
Name: B, dtype: float64

In [35]:
print(df["B"].std())

0.408248290463863

In [36]:
print(df["B"].unique())

[2.  2.5 3. ]

In [37]:
print(df["B"].nunique())

3

In [38]:
import pandas as pd

employee = {
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Ravi"],
    "Department": ["IT", "HR", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 47000]
}

df = pd.DataFrame(employee)

summary = df.groupby("Department")["Salary"].agg(
    ["count", "mean", "max", "min"]
)

print(summary)

summary.to_excel("Department_Summary.xlsx")
print("Excel file created successfully!")

            count     mean    max    min
Department
HR              2  46000.0  47000  45000
IT              2  55000.0  60000  50000
Sales           1  55000.0  55000  55000
Excel file created successfully!

In [40]:
import pandas as pd 
# Read Dataset 
df = pd.read_csv("employees.csv") 
# Display First Records 
print(df.head()) 
# Basic Information 
print(df.info()) 
 
# Highest Salary 
print("Highest Salary:",df["Salary"].max()) 
 
# Average Salary 
print("Average Salary:",df["Salary"].mean()) 
 
# Department Wise Salary 
print(df.groupby("Department")["Salary"].mean()) 
 
# Employees earning above 60000 
high=df[df["Salary"]>60000] 
 
print(high) 
 
# Sort Employees 
df=df.sort_values(by="Salary", 
                  ascending=False) 
 
# Save Report 
df.to_excel("Employee_Report.xlsx", 
            index=False) 
 
print("Report Generated Successfully")

   Emp_ID   Name Department  Salary  Experience
0     101  Rohit         HR   45000           2
1     102  Priya         IT   65000           5
2     103   Amit    Finance   70000           7
3     104   Neha         IT   60000           4
4     105    Raj      Sales   55000           3
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      5 non-null      int64
 1   Name        5 non-null      str
 2   Department  5 non-null      str
 3   Salary      5 non-null      int64
 4   Experience  5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 332.0 bytes
None
Highest Salary: 70000
Average Salary: 59000.0
Department
Finance    70000.0
HR         45000.0
IT         62500.0
Sales      55000.0
Name: Salary, dtype: float64
   Emp_ID   Name Department  Salary  Experience
1     102  Priya         IT   65000           5
2     103   Amit    Finance   70000           7
Report Generated Successfully

In [42]:
import pandas as pd 
 
data = { 
    "Employee":["Amit","Rahul","Priya","John","Neha","Riya","Karan","David"], 
    "Department":["HR","IT","IT","Sales","HR","Sales","IT","HR"], 
    
"City":["Delhi","Delhi","Mumbai","Mumbai","Delhi","Mumbai","Delhi","Mumbai"], 
    "Salary":[35000,50000,60000,45000,40000,55000,65000,38000], 
    "Experience":[2,5,6,4,3,5,8,2] 
} 
 
df = pd.DataFrame(data) 
print(df)

  Employee Department    City  Salary  Experience
0     Amit         HR   Delhi   35000           2
1    Rahul         IT   Delhi   50000           5
2    Priya         IT  Mumbai   60000           6
3     John      Sales  Mumbai   45000           4
4     Neha         HR   Delhi   40000           3
5     Riya      Sales  Mumbai   55000           5
6    Karan         IT   Delhi   65000           8
7    David         HR  Mumbai   38000           2

In [43]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    aggfunc="mean" 
) 
 
print(pivot)

                  Salary
Department
HR          37666.666667
IT          58333.333333
Sales       50000.000000

In [44]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    aggfunc="max" 
) 
 
print(pivot)

            Salary
Department
HR           40000
IT           65000
Sales        55000

In [45]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    aggfunc="sum" 
) 
 
print(pivot)

            Salary
Department
HR          113000
IT          175000
Sales       100000

In [46]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    columns="City",
    aggfunc="mean" 
) 
 
print(pivot)

City          Delhi   Mumbai
Department
HR          37500.0  38000.0
IT          57500.0  60000.0
Sales           NaN  50000.0

In [47]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    columns="City", 
    aggfunc="sum" 
) 
 
print(pivot)

City           Delhi    Mumbai
Department
HR           75000.0   38000.0
IT          115000.0   60000.0
Sales            NaN  100000.0

In [48]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    columns="City", 
    aggfunc="sum", 
    fill_value=0 
) 
 
print(pivot)

City         Delhi  Mumbai
Department
HR           75000   38000
IT          115000   60000
Sales            0  100000

In [49]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    aggfunc=["sum","mean","max","min"] 
) 
 
print(pivot)

               sum          mean    max    min
            Salary        Salary Salary Salary
Department
HR          113000  37666.666667  40000  35000
IT          175000  58333.333333  65000  50000
Sales       100000  50000.000000  55000  45000

In [50]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    aggfunc="count" 
) 
 
print(pivot)

            Salary
Department
HR               3
IT               3
Sales            2

In [56]:
pivot = pd.pivot_table( 
    df, 
    values=["Salary","Experience"],
    index="City", 
    aggfunc="mean" 
) 
 
print(pivot)

        Experience   Salary
City
Delhi         4.50  47500.0
Mumbai        4.25  49500.0

In [57]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index="Department", 
    aggfunc="sum", 
    margins=True 
) 
 
print(pivot)

            Salary
Department
HR          113000
IT          175000
Sales       100000
All         388000

In [58]:
pivot = pd.pivot_table( 
    df, 
    values="Salary", 
    index=["Department","City"], 
    aggfunc="mean" 
) 
print(pivot)

                    Salary
Department City
HR         Delhi   37500.0
           Mumbai  38000.0
IT         Delhi   57500.0
           Mumbai  60000.0
Sales      Mumbai  50000.0

In [60]:
import pandas as pd 
 
students = { 
    "Student":["A","B","C","D","E","F","G","H"], 
    "Class":["10","10","10","9","9","9","8","8"], 
    
"Subject":["Math","Math","Science","Math","Science","Math","Science","Math"], 
    "Marks":[85,90,88,75,80,78,92,89] 
} 
 
df = pd.DataFrame(students) 
 
pivot = pd.pivot_table( 
    df, 
    values="Marks", 
    index="Class", 
    columns="Subject", 
    aggfunc="mean", 
    fill_value=0 
) 
 
print(pivot)

Subject  Math  Science
Class
10       87.5     88.0
8        89.0     92.0
9        76.5     80.0

In [61]:
import pandas as pd 
 
sales = { 
    "Month":["Jan","Jan","Feb","Feb","Mar","Mar"], 
    "Product":["Laptop","Mobile","Laptop","Mobile","Laptop","Mobile"], 
    "Region":["East","East","West","West","East","West"], 
    "Sales":[50000,30000,60000,35000,55000,40000] 
} 
 
df = pd.DataFrame(sales) 
 
pivot = pd.pivot_table( 
    df, 
    values="Sales", 
    index="Month", 
    columns="Product", 
    aggfunc="sum", 
    margins=True, 
    fill_value=0 
) 
 
print(pivot)

Product  Laptop  Mobile     All
Month
Feb       60000   35000   95000
Jan       50000   30000   80000
Mar       55000   40000   95000
All      165000  105000  270000